feat: 주차장 정보를 담은 `Card` 컴포넌트를 구현한다.
parkingkim/parkingkim-webapp pull request #19
Opened 2024-01-30 04:28 UTC by regularPark

## 구현 사항

- 와이어프레임 디자인에 맞추어 주차장 정보를 담은 카드를 구현했습니다.
- 사용자 현위치를 구하지 못했을때는 기본위치(SK 모빌리티)으로 이동하게 하였습니다.

![스크린샷 2024-01-30 오후 1 26 49](https://github.com/parkingkim/parkingkim-webapp/assets/90092440/d784a42b-c218-4ba2-98d6-11fab7798f5e)

2024-01-31 16:12 UTC, kangyeongmin requested changes
수고하셨습니다 레고레고 ㅎㅎ😆😆

2024-01-31 16:12 UTC, kangyeongmin commented on src/components/Card/index.tsx
> +const Card = ({ title, imgUrl, price, ETA, isPublic, isFavorite }: CardProps) => {
Card 라는 이름이 너무 범위가 넓어서 좀 좁혀주면 좋을거 같아요!

2024-01-31 16:12 UTC, kangyeongmin commented on src/components/Card/Badge.tsx
> +      {<BadgeWrapper>{isPublic ? '공영' : '민영'} 주차장</BadgeWrapper>}
isPublic prop이 없으면 무조건 민영으로 분류되는것이 맞나용??

아니면 
이것도 price와 ETA처럼 앞의 조건문을 하나 더 두어야하지 않나 싶습니다!

2024-01-31 16:12 UTC, kangyeongmin commented on src/constants/index.ts
> +export const INIT_LNG = 126.98502302169841;
요건 어떤값으로 초기화 되는건가요??

2024-02-01 11:06 UTC, regularPark commented on src/constants/index.ts
> +export const INIT_LNG = 126.98502302169841;
티맵 api에서 현위치를 추적하지 못할 때 티맵 api 초기 위치로 변경합니다!

2024-02-01 11:07 UTC, regularPark commented on src/components/Card/Badge.tsx
> +      {<BadgeWrapper>{isPublic ? '공영' : '민영'} 주차장</BadgeWrapper>}
해당 부분 어제 백엔드와 api 명세 회의할 때 논의한 부분인데요. 불리언 말고 스트링 값을 받을 것 같아요. 곧 수정하겠습니다~

2024-02-03 23:12 UTC, regularPark commented on src/components/Card/index.tsx
> +const Card = ({ title, imgUrl, price, ETA, isPublic, isFavorite }: CardProps) => {
`ParkingLotCard`로 변경하였습니다~

[519b61f](https://github.com/parkingkim/parkingkim-webapp/pull/19/commits/519b61f81fd73f6ac3058fc80402165281d9561d)

2024-02-03 23:13 UTC, regularPark commented on src/components/Card/Badge.tsx
> +      {<BadgeWrapper>{isPublic ? '공영' : '민영'} 주차장</BadgeWrapper>}
`isPublic` -> `parkingType`으로 변경

[ca22c4e](https://github.com/parkingkim/parkingkim-webapp/pull/19/commits/ca22c4ee744ccbbd8baa2411c0d738cfb66be20a)

2024-02-04 00:07 UTC, kangyeongmin approved these changes
리뷰 반영 좋아요~

명세가 나왔군요 ㅎㅎ 이제 진짜 달려야할차례 ,,,, 💪

2024-02-04 00:11 UTC, merged