feat: 현재 경도, 위도로 사용해 주소를 받아오는 기능을 구현한다.
parkingkim/parkingkim-webapp pull request #42
Opened 2024-02-27 08:19 UTC by regularPark

## 기능 구현

- 티맵 api를 사용하여 현위치 경도, 위도를 사용해 주소를 반환하는 로직을 구현했습니다.
- 줌인, 줌아웃 버튼을 통해 지도의 축척을 조절할 수 있게 구현했습니다.

## 구현 화면

### 현위치 버튼 클릭
![curlocation](https://github.com/parkingkim/parkingkim-webapp/assets/90092440/b733d0e8-5a31-4341-91a2-79f7ac20d5d2)

### 앱 시작시 현위치로 이동 및 현위치 주소가 표시되는 모습
![initApp](https://github.com/parkingkim/parkingkim-webapp/assets/90092440/51726ff6-cb05-4142-9698-618d15cd169e)

### 버튼을 통한 축척 조절
![zoomInOut](https://github.com/parkingkim/parkingkim-webapp/assets/90092440/d2b8e06b-8c9c-4ba0-941e-642ea664804c)

closes #41

2024-03-05 14:38 UTC, kangyeongmin requested changes
레고 제가 많이 늦엇죠..?😓😅
~~개강전에 전주로 가족여행이 다녀오고 그다음 바로 개강이 어쩌고 저쩌고 변명중,,,~~
면목이 없어요 ㅎㅎ

zustand를 사용하여 현위치로 set 하는 로직 잘봤습니다!
일단 너무 늦은거 같아서 적은 리뷰 먼저 드릴게요.

2024-03-05 14:38 UTC, kangyeongmin commented on src/components/Map.tsx
>        makeUserMaker();
유저의 위치를 먼저 찾을때까지 기다렷다가 set 할순 없을까요?
가끔씩 지도가 티맵모빌리티 위치(37.5652045, 126.98702028)가 1초 떳다가 사용자의 위치로 넘어가는 부분이 ux 측면에서 좋지 않은 거 같아요!

<img width="841" alt="스크린샷 2024-03-05 오후 11 35 01" src="https://github.com/parkingkim/parkingkim-webapp/assets/62367797/00744cea-7132-4d09-b1e5-d251453c7be0">

2024-03-06 14:14 UTC, regularPark commented on src/components/Map.tsx
>        makeUserMaker();
그래서 최초 화면 현재위치로 바꿨구요! 이전에 내 주차장, 메뉴 등 다른 페이지로 갔다가 돌아왔을때 지도가 새롭게 불러와져서 UX가 좋지 않았던 점, 라우터의 Root에서 지도 컴포넌트를 불러오도록 하였습니다.

2024-03-07 09:55 UTC, kangyeongmin approved these changes

2024-03-07 09:55 UTC, kangyeongmin commented on src/components/Map.tsx
> +        center: new Tmapv3.LatLng(userLocation.lat, userLocation.lng),
👍🏻👍🏻

2024-03-07 09:56 UTC, kangyeongmin commented on src/components/Map.tsx
>        makeUserMaker();
정말 좋습니다!!

2024-03-12 03:01 UTC, merged