feat: 회원가입 구현
parkingkim/parkingkim-webapp pull request #48
Opened 2024-03-09 03:59 UTC by kangyeongmin

<img width="444" alt="스크린샷 2024-03-09 오후 12 59 41" src="https://github.com/parkingkim/parkingkim-webapp/assets/62367797/edb891db-2e7d-4ce5-b141-e5f96a0cc77b">

2024-03-10 15:01 UTC, regularPark requested changes
고생하셨습니다!👍👍 특히 입력부에서 커링 사용하신 로직 인상깊게 봤읍니다. 멋져요 롸잇✨

마크업이 대부분인지라 로직적으로 피드백 드릴 부분 없고, 기획적으로 논의가 필요한 부분에 대한 피드백만 좀 남겨봤습니다.

+++ 실행해보니 버튼이 요렇게 생겼더라구여!
![스크린샷 2024-03-10 오후 11 40 02](https://github.com/parkingkim/parkingkim-webapp/assets/90092440/a7dc8e12-7dcc-49ca-8c38-f2bbfbe239e3)

2024-03-10 15:01 UTC, regularPark commented on src/router.tsx
>        { path: '/profile', element: <Profile /> },
profile부터 아래의 페이지들은 BottomTabBarRoot로 이동시켜주세요!

2024-03-20 07:28 UTC, kangyeongmin commented on src/components/ModalPortal.tsx
> +};
모달이나 바텀시트, 알러트 처럼, html 상에 단독적으로 존재해야하는 구조에 모두 적용될 수 있을거 같아서 컴포넌트화 해두었습니다!!

2024-03-20 07:28 UTC, kangyeongmin commented on src/pages/Signup/index.tsx
> +        break;
맞습니다!

2024-03-20 07:32 UTC, kangyeongmin commented
> +++ 실행해보니 버튼이 요렇게 생겼더라구여!

앞 전 pr에서 버튼컴포넌트를 수정했어서, 머지되고 난 후 rebase 하려고 해서 수정 전 모양으로 뜨고 있습니다!
<img width="490" alt="스크린샷 2024-03-20 오후 4 32 43" src="https://github.com/parkingkim/parkingkim-webapp/assets/62367797/b761d63f-add7-47ad-a507-fa0aacedc639">
현재는 요런 상태입니다!

2024-03-20 07:33 UTC, merged