feat: 검색 기능을 구현한다.
parkingkim/parkingkim-webapp pull request #53
Opened 2024-04-01 12:32 UTC by regularPark

## 구현한 기능
- 도로명주소, 건물명 등으로 검색 가능한 api를 사용하여 검색기능을 구현했습니다.
- 검색이후 결과에서 원하는 목적지를 선택하면 지도가 그 위치로 이동합니다.

## 구현 화면
<img width="282" alt="스크린샷 2024-04-01 오후 9 16 57" src="https://github.com/parkingkim/parkingkim-webapp/assets/90092440/42adb34f-3466-4c09-a995-73a551f268b1">
<img width="284" alt="스크린샷 2024-04-01 오후 9 17 18" src="https://github.com/parkingkim/parkingkim-webapp/assets/90092440/b9db264a-37b4-4da7-b96d-ed26951928a8">

2024-04-02 10:58 UTC, kangyeongmin requested changes
레고 바쁘신와중에도 이렇게 또 pr을...
정말 수고하셔씁니다!!

검색기능 아주 멋져요. 
궁금한게 있어서 답변달아주시면 재리뷰 남기러 오겠습니다~

2024-04-02 10:58 UTC, kangyeongmin commented on src/components/SearchItem.tsx
> +    );
로직이 복잡해서 함수로 분리하는게 좋을거 같습니당!

2024-04-02 10:58 UTC, kangyeongmin commented on src/pages/home/components/SearchContent.tsx
> +      ) : (
early return 시켜버리면 어떨까요?

2024-04-02 10:58 UTC, kangyeongmin commented on src/components/BottomSheet/index.tsx
> +  isResult?: boolean;
이거는 어디에 필요한 prop인지 궁금해요!

2024-04-02 10:58 UTC, kangyeongmin commented on src/pages/home/hooks/useSearch.ts
> +        });
노션에 문서 추가된 알림을 보았어서 axios 도입하시는줄 알앗는데, 아니엇던가용?!

2024-04-02 13:57 UTC, regularPark commented on src/components/BottomSheet/index.tsx
> +  isResult?: boolean;
이거는 경로안내를 위한 props인데 제가 경로안내를 다른 PR 빼려다가 남아있는 관련 코드들을 그대로 두었네요😅

2024-04-02 14:00 UTC, regularPark commented on src/pages/home/hooks/useSearch.ts
> +        });
오잉 axios 도입은 생각해본적 없는데용? 지금 노션 확인해보는데 없숨다!

2024-04-02 14:01 UTC, regularPark commented on src/pages/home/components/SearchContent.tsx
> +      ) : (
좋습니다👍

2024-04-02 14:17 UTC, regularPark commented on src/components/SearchItem.tsx
> +    );
[f109f2f](https://github.com/parkingkim/parkingkim-webapp/pull/53/commits/f109f2f6b21d1f2be72e435726393bd810db83e6)

분리 완

2024-04-03 05:42 UTC, kangyeongmin commented on src/components/BottomSheet/index.tsx
> +  isResult?: boolean;
아 그렇군요! 
근데 또다른 방안으로 그냥 저 컴포넌트를 Home page에 종속 시켜버리고 prop이 늘어나더라고 더 고도화시키는 방안으로 가는 것도 나쁘지 않아보여요. 그 이유는 결과에 따라서 높이가 달라지는 bottomSheet가 저 곳에서만 쓰이기도 하고, 'BottomSheet'이라는 범용적인 이름을 갖기에는 하는 일이 너무 뾰족하다고 생각이 드네요!

2024-04-03 05:43 UTC, kangyeongmin commented on src/pages/home/hooks/useSearch.ts
> +        });
에엥????!
허것스

2024-04-03 05:44 UTC, kangyeongmin approved these changes
레고 리뷰 반영하신것들 확인했습니다~

axios는 정말 띄용이네요.
이참에 도입하는 거 어떠신가요?!

2024-04-03 07:03 UTC, merged