feat: 경로안내 기능을 구현한다.
parkingkim/parkingkim-webapp pull request #55
Opened 2024-04-30 06:59 UTC by regularPark

## 구현한 기능

오래 기다리셨습니다! 아무래도 오래 묵힌 기능이다보니 변경된 코드가 정말 많을 겁니다 ㅎㅎ

- 마침내 경로 안내 기능을 구현하였습니다.
   - 현위치 -> 주차장, 주차장 -> 목적지까지의 경로 두가지를 합쳐 경로를 그려줍니다.
- 가고자 하는 주차장을 선택하였을때 나머지 주차장이 지도에서 보이지 않게 하는 기능은 아직 구현하지 못했습니다.
- 목적지까지 도보로 이동하는 시간은 백엔드 쪽에서 아직 미완성인 상태라 티맵의 데이터를 가져다 씁니다.

## 구현한 화면
<img width="226" alt="스크린샷 2024-04-30 오후 3 54 39" src="https://github.com/parkingkim/parkingkim-webapp/assets/90092440/643c7e8e-ab60-4406-b4b5-1029a235cc3d">

<img width="250" alt="스크린샷 2024-04-30 오후 3 53 50" src="https://github.com/parkingkim/parkingkim-webapp/assets/90092440/f462586e-f0d1-4d93-be6b-26554a26fb49">

<img width="250" alt="스크린샷 2024-04-30 오후 3 54 03" src="https://github.com/parkingkim/parkingkim-webapp/assets/90092440/ba56f7ad-dbc8-4862-936a-afafd016cfd8">

2024-05-01 17:00 UTC, kangyeongmin requested changes
와....말잇못...역대 제가 본 최대량 pr 인거 같아요...
티맵이랑 찐한 협업하셨네요...레고...이정도면 Tmap 입사도 가넝할듯...
간단한 코드리뷰 남겼습네다...
재요청해주세요 😊

2024-05-01 17:00 UTC, kangyeongmin commented on src/components/SearchBar.tsx
>          <IconWrapper>
두부분이 많이 다른 html이라 한 부분은 위에서 early return 하시는게 더 깔끔할거 같습니다!
그리고 onClick에 핸들러함수를 그냥 넣어주지 않고 저렇게 넣어주신 이유가 있나요??

2024-05-01 17:00 UTC, kangyeongmin commented on src/hooks/useDrawLine.ts
> +        },
fetch 로직은 axios로 다 통일하는것이 어떨까용

2024-05-01 17:00 UTC, kangyeongmin commented on src/hooks/useDrawLine.ts
> +            }
switch case 문이 더 어울릴거 같습니다!

2024-05-01 17:00 UTC, kangyeongmin commented on src/hooks/useDrawLine.ts
> +            }
위에 비슷한 로직이 있어서 색깔 반환하는 util함수로 빼도 좋을 것 같아요!

2024-05-01 17:00 UTC, kangyeongmin commented on src/hooks/useDrawLine.ts
> +            lineArr.push(polyLine);
요것도 반복되는데 추출할 수 있으면 분리해서 재사용해도 좋을거 같습니다

2024-05-01 17:00 UTC, kangyeongmin commented on src/pages/home/components/ParkingLotsList.tsx
> +  };
👍🏻 요거 두개 순서 바꿔줘도 좀더 깔끔할거 같아요!

2024-05-01 17:00 UTC, kangyeongmin commented on src/pages/home/components/ResultContent.tsx
> +  if (selectedParkingLot !== -1)
상수화 해주세용~

2024-05-02 01:38 UTC, regularPark commented on src/hooks/useDrawLine.ts
> +        },
반영하였습니다!

[788b003](https://github.com/parkingkim/parkingkim-webapp/pull/55/commits/788b003a98fc59e5e8724652608e49e828e8ca32)

2024-05-02 01:38 UTC, regularPark commented on src/hooks/useDrawLine.ts
> +            lineArr.push(polyLine);
반복되는 로직들 내부에서 함수로 분리하여 리팩터링했습니다😁

[54a9b76](https://github.com/parkingkim/parkingkim-webapp/pull/55/commits/54a9b763bde45b43e30d3269cdd800ec44a94cef)

2024-05-02 09:56 UTC, kangyeongmin approved these changes
어프룹

2024-05-02 10:35 UTC, merged