feat: 메뉴의 최종 디자인을 반영한다.
parkingkim/parkingkim-webapp pull request #57
Opened 2024-05-01 09:33 UTC by regularPark

디자인 반영이라 딱히 말씀드릴만한 기능 구현 사항은 없습니다!😅

- 탭바
<img width="373" alt="스크린샷 2024-05-01 오후 6 25 05" src="https://github.com/parkingkim/parkingkim-webapp/assets/90092440/d2d9ec79-d3e0-43e2-b2de-f7b2f718a676">

- 리뷰관리
<img width="378" alt="스크린샷 2024-05-01 오후 5 24 32" src="https://github.com/parkingkim/parkingkim-webapp/assets/90092440/d535de00-3e6d-449f-9c7d-4ec3ef30c98f">

- 내 주차장
<img width="380" alt="스크린샷 2024-05-01 오후 5 23 17" src="https://github.com/parkingkim/parkingkim-webapp/assets/90092440/5de9a14b-38f7-4a33-85c3-8bf885a00e19">

- 비밀번호 변경
<img width="380" alt="스크린샷 2024-05-01 오후 5 22 58" src="https://github.com/parkingkim/parkingkim-webapp/assets/90092440/c362e8ba-3f50-4e82-b04c-f490ae422f2a">

- 집/회사 주소 관리
<img width="380" alt="스크린샷 2024-05-01 오후 5 22 32" src="https://github.com/parkingkim/parkingkim-webapp/assets/90092440/6355f438-b3dc-4d64-83f7-08814be062ba">

- 주소 검색
<img width="379" alt="스크린샷 2024-05-01 오후 5 21 53" src="https://github.com/parkingkim/parkingkim-webapp/assets/90092440/41b0871c-fc7a-410a-92cb-0730989739ab">

- 쿠폰
<img width="379" alt="스크린샷 2024-05-01 오후 5 22 47" src="https://github.com/parkingkim/parkingkim-webapp/assets/90092440/a9bc8777-d87b-49d5-9208-91f314f60692">

2024-05-01 17:24 UTC, kangyeongmin requested changes
여기도 엄청나게 고생하셧네유,,, 
👏👏👏👏👏👏
레고의개발은현실이된다,,,

2024-05-01 17:24 UTC, kangyeongmin commented on src/pages/Menu/Profile/ChangePassword/index.tsx
> +            newPassword !== againPassword
util로 분리해도 좋을거 같습니당

2024-05-01 17:24 UTC, kangyeongmin commented on src/pages/Menu/Profile/hook/usePassword.ts
> +  };
validate로직과 set 로직이 분리되도 좋을거 같아요!
그리고 IsCurPasswordValid을 상태로 안가지고 있어도 isValidPassword(curPassword)함수를 사용처에서 바로 넣어줘도될 거 같아요!!

2024-05-01 17:24 UTC, kangyeongmin commented on src/pages/Menu/Profile/index.tsx
> +          {user?.email}
옵셔널 피할 수 없을까용?

2024-05-01 17:24 UTC, kangyeongmin commented on src/pages/Menu/FrequentDestinations/index.tsx
> +  };
이 패턴 계속 반복되는거 가튼데, 깔쌈하게 처리되는 방법 없을까요?! 
근데 두 상태가 항상 같은 상태를 가질 거 같은데, 이렇게 다른 변수로 관리되어야 하는 이유는 무엇인가요??(궁금)

2024-05-02 01:44 UTC, regularPark commented on src/pages/Menu/FrequentDestinations/index.tsx
> +  };
이 로직은 `현위치로 주소 설정` 버튼을 누르면 현위치가 집/회사 주소로 각각 현재 선택된 탭에 따라 분기되는 로직입니다.

따라서 같은 데이터를 사용하지만, 전혀 다른 의미를 가지고 있습니다!

2024-05-02 03:01 UTC, regularPark commented on src/pages/Menu/Profile/hook/usePassword.ts
> +  };
[7e8719e](https://github.com/parkingkim/parkingkim-webapp/pull/57/commits/7e8719e38a7a5efc4b833b6dd2f6a09594860f1f)
[873e043](https://github.com/parkingkim/parkingkim-webapp/pull/57/commits/873e0436472cd97058d8a448938adc9bb0338b2e)

`ChangePassword` 컴포넌트에서 상태를 선언해주는 것에 대한 차이를 크게 느끼지는 못해서 새로 리팩터링을 해보았는데 라잇의 생각은 어떠신가여!

2024-05-02 03:01 UTC, regularPark commented on src/pages/Menu/Profile/ChangePassword/index.tsx
> +            newPassword !== againPassword
[873e043](https://github.com/parkingkim/parkingkim-webapp/pull/57/commits/873e0436472cd97058d8a448938adc9bb0338b2e)

유틸로 분리하기에는 파라미터가 여섯개라서 사용처에서 함수로 분리해보았습니다😁

2024-05-02 03:03 UTC, regularPark commented on src/pages/Menu/Profile/index.tsx
> +          {user?.email}
위 상황을 해결하려면

사용자가 비회원 상태로 메뉴에 접근했을때
1. 접근을 막거나 
2. 디폴트값을 정해주는 방안

둘 중에 선택해야 할 것 같습니다! 라잇의 생각은 어떠신가여?

2024-05-02 10:00 UTC, kangyeongmin approved these changes
어프룹__

2024-05-02 10:13 UTC, merged